### ISSUE TITLE
Investigate failing test case

### ISSUE THREAD

**Issue by hechth** [RECETOX/gc-meox-tms#28]
https://github.com/RECETOX/gc-meox-tms/actions/runs/6611377685/job/17955136541

**Comment by hechth** [comment]
@wverastegui maybe you could have a look at this?

**Comment by wverastegui** [comment]
@hechth , log file is expired in the above link. Running the test locally, failing seems to be related to the not deterministic nature of the function add_derivatization_groups(). When the randomness in the function is eliminated, tests pass.
